const flagsData = [
    { code: "af", name: "Afghanistan", imageUrl: "flags\\af.png" },
    { code: "al", name: "Albania", imageUrl: "flags\\al.png" },
    { code: "dz", name: "Algeria", imageUrl: "flags\\dz.png" },
    { code: "ad", name: "Andorra", imageUrl: "flags\\ad.png" },
    { code: "ao", name: "Angola", imageUrl: "flags\\ao.png" },
    { code: "ag", name: "Antigua and Barbuda", imageUrl: "flags\\ag.png" },
    { code: "ar", name: "Argentina", imageUrl: "flags\\ar.png" },

    { code: "am", name: "Armenia", imageUrl: "flags\\am.png" },
    { code: "au", name: "Australia", imageUrl: "flags\\au.png" },
    { code: "at", name: "Austria", imageUrl: "flags\\at.png" },
    { code: "az", name: "Azerbaijan", imageUrl: "flags\\az.png" },
    { code: "bs", name: "Bahamas", imageUrl: "flags\\bs.png" },
    { code: "bh", name: "Bahrain", imageUrl: "flags\\bh.png" },
    { code: "bd", name: "Bangladesh", imageUrl: "flags\\bd.png" },

    { code: "bb", name: "Barbados", imageUrl: "flags\\bb.png" },
    { code: "by", name: "Belarus", imageUrl: "flags\\by.png" },
    { code: "be", name: "Belgium", imageUrl: "flags\\be.png" },
    { code: "bz", name: "Belize", imageUrl: "flags\\bz.png" },
    { code: "bj", name: "Benin", imageUrl: "flags\\bj.png" },
    { code: "bt", name: "Bhutan", imageUrl: "flags\\bt.png" },
    { code: "bo", name: "Bolivia", imageUrl: "flags\\bo.png" },

    { code: "ba", name: "Bosnia and Herzegovina", imageUrl: "flags\\ba.png" },
    { code: "bw", name: "Botswana", imageUrl: "flags\\bw.png" },
    { code: "br", name: "Brazil", imageUrl: "flags\\br.png" },
    { code: "bn", name: "Brunei", imageUrl: "flags\\bn.png" },
    { code: "bg", name: "Bulgaria", imageUrl: "flags\\bg.png" },
    { code: "bf", name: "Burkina Faso", imageUrl: "flags\\bf.png" },
    { code: "bi", name: "Burundi", imageUrl: "flags\\bi.png" },
    
   
    { code: "kh", name: "Cambodia", imageUrl: "flags\\kh.png" },
    { code: "cm", name: "Cameroon", imageUrl: "flags\\cm.png" },
    { code: "ca", name: "Canada", imageUrl: "flags\\ca.png" },
    { code: "cv", name: "Cape Verde", imageUrl: "flags\\cv.png" },
    { code: "cf", name: "Central African Republic", imageUrl: "flags\\cf.png" },
    { code: "td", name: "Chad", imageUrl: "flags\\td.png" },
    { code: "cl", name: "Chile", imageUrl: "flags\\cl.png" },

    { code: "cn", name: "China", imageUrl: "flags\\cn.png" },
    { code: "co", name: "Colombia", imageUrl: "flags\\co.png" },
    { code: "km", name: "Comoros", imageUrl: "flags\\km.png" },
    { code: "cg", name: "Congo", imageUrl: "flags\\cg.png" },
    { code: "cd", name: "Congo, The Democratic Republic of the", imageUrl: "flags\\cd.png" },
    { code: "cr", name: "Costa Rica", imageUrl: "flags\\cr.png" },
    { code: "ci", name: "C\u00f4te d'Ivoire", imageUrl: "flags\\ci.png" },

    { code: "hr", name: "Croatia", imageUrl: "flags\\hr.png" },
    { code: "cu", name: "Cuba", imageUrl: "flags\\cu.png" },
    { code: "cy", name: "Cyprus", imageUrl: "flags\\cy.png" },
    { code: "cz", name: "Czech Republic", imageUrl: "flags\\cz.png" },
    { code: "dk", name: "Denmark", imageUrl: "flags\\dk.png" },
    { code: "dj", name: "Djibouti", imageUrl: "flags\\dj.png" },
    { code: "dm", name: "Dominica", imageUrl: "flags\\dm.png" },

    { code: "do", name: "Dominican Republic", imageUrl: "flags\\do.png" },
    { code: "tl", name: "East Timor", imageUrl: "flags\\tl.png" },
    { code: "ec", name: "Ecuador", imageUrl: "flags\\ec.png" },
    { code: "eg", name: "Egypt", imageUrl: "flags\\eg.png" },
    { code: "sv", name: "El Salvador", imageUrl: "flags\\sv.png" },
    { code: "gq", name: "Equatorial Guinea", imageUrl: "flags\\gq.png" },
    { code: "er", name: "Eritrea", imageUrl: "flags\\er.png" },

    { code: "ee", name: "Estonia", imageUrl: "flags\\ee.png" },
    { code: "et", name: "Ethiopia", imageUrl: "flags\\et.png" },
    { code: "fj", name: "Fiji", imageUrl: "flags\\fj.png" },
    { code: "fi", name: "Finland", imageUrl: "flags\\fi.png" },
    { code: "fr", name: "France", imageUrl: "flags\\fr.png" },
    { code: "gf", name: "French Guiana", imageUrl: "flags\\gf.png" },
    { code: "ga", name: "Gabon", imageUrl: "flags\\ga.png" },

    { code: "gm", name: "Gambia", imageUrl: "flags\\gm.png" },
    { code: "ge", name: "Georgia", imageUrl: "flags\\ge.png" },
    { code: "de", name: "Germany", imageUrl: "flags\\de.png" },
    { code: "gh", name: "Ghana", imageUrl: "flags\\gh.png" },
    { code: "gr", name: "Greece", imageUrl: "flags\\gr.png" },
    { code: "gl", name: "Greenland", imageUrl: "flags\\gl.png" },
    { code: "gd", name: "Grenada", imageUrl: "flags\\gd.png" },

    { code: "gt", name: "Guatemala", imageUrl: "flags\\gt.png" },
    { code: "gn", name: "Guinea", imageUrl: "flags\\gn.png" },
    { code: "gw", name: "Guinea-Bissau", imageUrl: "flags\\gw.png" },
    { code: "gy", name: "Guyana", imageUrl: "flags\\gy.png" },
    { code: "ht", name: "Haiti", imageUrl: "flags\\ht.png" },
    { code: "hn", name: "Honduras", imageUrl: "flags\\hn.png" },
    { code: "hu", name: "Hungary", imageUrl: "flags\\hu.png" },

    { code: "is", name: "Iceland", imageUrl: "flags\\is.png" },
    { code: "in", name: "India", imageUrl: "flags\\in.png" },
    { code: "id", name: "Indonesia", imageUrl: "flags\\id.png" },
    { code: "ir", name: "Iran", imageUrl: "flags\\ir.png" },
    { code: "iq", name: "Iraq", imageUrl: "flags\\iq.png" },
    { code: "ie", name: "Ireland", imageUrl: "flags\\ie.png" },
    { code: "il", name: "Israel", imageUrl: "flags\\il.png" },

    { code: "it", name: "Italy", imageUrl: "flags\\it.png" },
    { code: "jm", name: "Jamaica", imageUrl: "flags\\jm.png" },
    { code: "jp", name: "Japan", imageUrl: "flags\\jp.png" },
    { code: "jo", name: "Jordan", imageUrl: "flags\\jo.png" },
    { code: "kz", name: "Kazakhstan", imageUrl: "flags\\kz.png" },
    { code: "ke", name: "Kenya", imageUrl: "flags\\ke.png" },
    { code: "ki", name: "Kiribati", imageUrl: "flags\\ki.png" },

    { code: "xk", name: "Kosovo", imageUrl: "flags\\xk.png" },
    { code: "kw", name: "Kuwait", imageUrl: "flags\\kw.png" },
    { code: "kg", name: "Kyrgyzstan", imageUrl: "flags\\kg.png" },
    { code: "la", name: "Laos", imageUrl: "flags\\la.png" },
    { code: "lv", name: "Latvia", imageUrl: "flags\\lv.png" },
    { code: "lb", name: "Lebanon", imageUrl: "flags\\lb.png" },
    { code: "ls", name: "Lesotho", imageUrl: "flags\\ls.png" },


    { code: "lr", name: "Liberia", imageUrl: "flags\\lr.png" },
    { code: "ly", name: "Libya", imageUrl: "flags\\ly.png" },
    { code: "li", name: "Liechtenstein", imageUrl: "flags\\li.png" },
    { code: "lt", name: "Lithuania", imageUrl: "flags\\lt.png" },
    { code: "lu", name: "Luxembourg", imageUrl: "flags\\lu.png" },
    { code: "mk", name: "Macedonia, Former Yugoslav Republic of", imageUrl: "flags\\mk.png" },
    { code: "mg", name: "Madagascar", imageUrl: "flags\\mg.png" },

    { code: "mw", name: "Malawi", imageUrl: "flags\\mw.png" },
    { code: "my", name: "Malaysia", imageUrl: "flags\\my.png" },
    { code: "mv", name: "Maldives", imageUrl: "flags\\mv.png" },
    { code: "ml", name: "Mali", imageUrl: "flags\\ml.png" },
    { code: "mt", name: "Malta", imageUrl: "flags\\mt.png" },
    { code: "mh", name: "Marshall Islands", imageUrl: "flags\\mh.png" },
    { code: "mr", name: "Mauritania", imageUrl: "flags\\mr.png" },

    { code: "mu", name: "Mauritius", imageUrl: "flags\\mu.png" },
    { code: "mx", name: "Mexico", imageUrl: "flags\\mx.png" },
    { code: "fm", name: "Micronesia", imageUrl: "flags\\fm.png" },
    { code: "md", name: "Moldova", imageUrl: "flags\\md.png" },
    { code: "mc", name: "Monaco", imageUrl: "flags\\mc.png" },
    { code: "mn", name: "Mongolia", imageUrl: "flags\\mn.png" },
    { code: "me", name: "Montenegro", imageUrl: "flags\\me.png" },

    { code: "ma", name: "Morocco", imageUrl: "flags\\ma.png" },
    { code: "mz", name: "Mozambique", imageUrl: "flags\\mz.png" },
    { code: "mm", name: "Myanmar", imageUrl: "flags\\mm.png" },
    { code: "na", name: "Namibia", imageUrl: "flags\\na.png" },
    { code: "nr", name: "Nauru", imageUrl: "flags\\nr.png" },
    { code: "np", name: "Nepal", imageUrl: "flags\\np.png" },
    { code: "nl", name: "Netherlands", imageUrl: "flags\\nl.png" },

    { code: "nz", name: "New Zealand", imageUrl: "flags\\nz.png" },
    { code: "ni", name: "Nicaragua", imageUrl: "flags\\ni.png" },
    { code: "ne", name: "Niger", imageUrl: "flags\\ne.png" },
    { code: "ng", name: "Nigeria", imageUrl: "flags\\ng.png" },
    { code: "kp", name: "North Korea", imageUrl: "flags\\kp.png" },
    { code: "no", name: "Norway", imageUrl: "flags\\no.png" },
    { code: "om", name: "Oman", imageUrl: "flags\\om.png" },
    
    { code: "pk", name: "Pakistan", imageUrl: "flags\\pk.png" },
    { code: "pw", name: "Palau", imageUrl: "flags\\pw.png" },
    { code: "ps", name: "Palestine", imageUrl: "flags\\ps.png" },
    { code: "pa", name: "Panama", imageUrl: "flags\\pa.png" },
    { code: "pg", name: "Papua New Guinea", imageUrl: "flags\\pg.png" },
    { code: "py", name: "Paraguay", imageUrl: "flags\\py.png" },
    { code: "pe", name: "Peru", imageUrl: "flags\\pe.png" },
    { code: "ph", name: "Philippines", imageUrl: "flags\\ph.png" },

    { code: "pl", name: "Poland", imageUrl: "flags\\pl.png" },
    { code: "pt", name: "Portugal", imageUrl: "flags\\pt.png" },
    { code: "qa", name: "Qatar", imageUrl: "flags\\qa.png" },
    { code: "ro", name: "Romania", imageUrl: "flags\\ro.png" },
    { code: "ru", name: "Russian Federation", imageUrl: "flags\\ru.png" },
    { code: "rw", name: "Rwanda", imageUrl: "flags\\rw.png" },
    { code: "kn", name: "St. Kitts and Nevis", imageUrl: "flags\\kn.png" },

    { code: "lc", name: "St. Lucia", imageUrl: "flags\\lc.png" },
    { code: "vc", name: "St. Vincent and the Grenadines", imageUrl: "flags\\vc.png" },
    { code: "ws", name: "Samoa", imageUrl: "flags\\ws.png" },
    { code: "sm", name: "San Marino", imageUrl: "flags\\sm.png" },
    { code: "st", name: "Sao Tome and Principe", imageUrl: "flags\\st.png" },
    { code: "sa", name: "Saudi Arabia", imageUrl: "flags\\sa.png" },
    { code: "sn", name: "Senegal", imageUrl: "flags\\sn.png" },

    { code: "rs", name: "Serbia", imageUrl: "flags\\rs.png" },
    { code: "sc", name: "Seychelles", imageUrl: "flags\\sc.png" },
    { code: "sl", name: "Sierra Leone", imageUrl: "flags\\sl.png" },
    { code: "sg", name: "Singapore", imageUrl: "flags\\sg.png" },
    { code: "sk", name: "Slovakia", imageUrl: "flags\\sk.png" },
    { code: "si", name: "Slovenia", imageUrl: "flags\\si.png" },
    { code: "sb", name: "Solomon Islands", imageUrl: "flags\\sb.png" },

    { code: "so", name: "Somalia", imageUrl: "flags\\so.png" },
    { code: "za", name: "South Africa", imageUrl: "flags\\za.png" },
    { code: "kr", name: "South Korea", imageUrl: "flags\\kr.png" },
    { code: "ss", name: "South Sudan", imageUrl: "flags\\ss.png" },
    { code: "es", name: "Spain", imageUrl: "flags\\es.png" },
    { code: "lk", name: "Sri Lanka", imageUrl: "flags\\lk.png" },
    { code: "sd", name: "Sudan", imageUrl: "flags\\sd.png" },
    
    { code: "sr", name: "Suriname", imageUrl: "flags\\sr.png" },
    { code: "sz", name: "Swaziland", imageUrl: "flags\\sz.png" },
    { code: "se", name: "Sweden", imageUrl: "flags\\se.png" },
    { code: "ch", name: "Switzerland", imageUrl: "flags\\ch.png" },
    { code: "sy", name: "Syria", imageUrl: "flags\\sy.png" },
    { code: "tw", name: "Taiwan", imageUrl: "flags\\tw.png" },
    { code: "tj", name: "Tajikistan", imageUrl: "flags\\tj.png" },

    { code: "tz", name: "Tanzania", imageUrl: "flags\\tz.png" },
    { code: "th", name: "Thailand", imageUrl: "flags\\th.png" },
    { code: "tg", name: "Togo", imageUrl: "flags\\tg.png" },
    { code: "to", name: "Tonga", imageUrl: "flags\\to.png" },
    { code: "tt", name: "Trinidad and Tobago", imageUrl: "flags\\tt.png" },
    { code: "tn", name: "Tunisia", imageUrl: "flags\\tn.png" },
    { code: "tr", name: "Turkey", imageUrl: "flags\\tr.png" },

    { code: "tm", name: "Turkmenistan", imageUrl: "flags\\tm.png" },
    { code: "ug", name: "Uganda", imageUrl: "flags\\ug.png" },
    { code: "ua", name: "Ukraine", imageUrl: "flags\\ua.png" },
    { code: "ae", name: "United Arab Emirates", imageUrl: "flags\\ae.png" },
    { code: "gb", name: "United Kingdom", imageUrl: "flags\\gb.png" },
    { code: "us", name: "United States of America", imageUrl: "flags\\us.png" },
    { code: "uy", name: "Uruguay", imageUrl: "flags\\uy.png" },

    { code: "uz", name: "Uzbekistan", imageUrl: "flags\\uz.png" },
    { code: "vu", name: "Vanuatu", imageUrl: "flags\\vu.png" },
    { code: "ve", name: "Venezuela", imageUrl: "flags\\ve.png" },
    { code: "vn", name: "Vietnam", imageUrl: "flags\\vn.png" },
    { code: "ye", name: "Yemen", imageUrl: "flags\\ye.png" },
    { code: "zm", name: "Zambia", imageUrl: "flags\\zm.png" },
    { code: "zw", name: "Zimbabwe", imageUrl: "flags\\zw.png" },
    
];